#!/usr/bin/env python3
"""Initialize a Knowledge Cat HTML deck project from the bundled template."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = SKILL_ROOT / "assets" / "html-template" / "index.html"


SAMPLE_SLIDES = """<section class="slide hero" data-layout="hero" data-title="Story comes before slide styling" data-role="Hook" data-theme="light">
  <div>
    <p class="kicker">Knowledge Cat PPT</p>
    <h1 class="hero-title">Story comes before slide styling</h1>
  </div>
  <p class="lead">A production deck starts with audience, outcome, story, and output lane.</p>
  <div class="footnote"><span>Source: deck brief</span><span>01</span></div>
</section>

<section class="slide statement" data-layout="statement" data-title="The right output lane prevents expensive rework" data-role="Mechanism" data-theme="dark">
  <div>
    <p class="kicker">Mechanism</p>
    <h2 class="action-title">The right output lane prevents expensive rework</h2>
  </div>
  <p class="lead">Native PPTX, HTML, and image-first decks solve different collaboration and fidelity problems.</p>
</section>

<section class="slide two-col" data-layout="closing-decision" data-title="Rendered QA turns a strong plan into a shippable deck" data-role="Closing" data-theme="light">
  <div>
    <p class="kicker">QA</p>
    <h2 class="action-title">Rendered QA turns a strong plan into a shippable deck</h2>
  </div>
  <div class="grid-3">
    <article class="card"><strong>Story</strong><p class="body">Action titles pass the ghost deck test.</p></article>
    <article class="card"><strong>Visual</strong><p class="body">Rendered slides have no collision or overflow.</p></article>
    <article class="card"><strong>Format</strong><p class="body">The file matches the user's real editing need.</p></article>
  </div>
</section>"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a Knowledge Cat HTML deck project.")
    parser.add_argument("target", help="Target project folder")
    parser.add_argument("--title", default="Knowledge Cat Deck", help="Deck title")
    parser.add_argument(
        "--empty",
        action="store_true",
        help="Keep the slide placeholder instead of writing sample slides",
    )
    args = parser.parse_args()

    target = Path(args.target).expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)
    (target / "images").mkdir(exist_ok=True)

    html = TEMPLATE.read_text(encoding="utf-8").replace("{{DECK_TITLE}}", args.title)
    if args.empty:
        html = html.replace("<!-- SLIDES_HERE -->", "<!-- SLIDES_HERE -->")
    else:
        html = html.replace("<!-- SLIDES_HERE -->", SAMPLE_SLIDES)
    (target / "index.html").write_text(html, encoding="utf-8")

    plan = {
        "deck": {
            "title": args.title,
            "audience": "Define the audience before production",
            "outcome": "Define the desired audience shift",
            "main_promise": "A deck is reliable when story, lane, design, and QA stay connected",
            "narrative_spine": "Problem -> mechanism -> QA",
            "output_lane": "html-deck",
            "format": "16:9 HTML",
            "slide_count": 3 if not args.empty else 0,
            "design_posture": "Strategic Minimal",
            "assumptions": ["Generated by init_deck_project.py"],
        },
        "slides": [] if args.empty else [
            {
                "number": 1,
                "layout": "hero",
                "action_title": "Story comes before slide styling",
                "role": "Hook",
                "key_message": "A production deck starts with audience, outcome, story, and output lane.",
                "evidence": ["Knowledge Cat PPT workflow"],
                "visual": "Hero title",
                "speaker_note": "Set the operating principle.",
                "source_refs": ["SKILL.md"],
                "asset_needs": [],
            },
            {
                "number": 2,
                "layout": "statement",
                "action_title": "The right output lane prevents expensive rework",
                "role": "Mechanism",
                "key_message": "Native PPTX, HTML, and image-first decks solve different problems.",
                "evidence": ["references/engine-routing.md"],
                "visual": "Statement slide",
                "speaker_note": "Explain lane selection.",
                "source_refs": ["references/engine-routing.md"],
                "asset_needs": [],
            },
            {
                "number": 3,
                "layout": "closing-decision",
                "action_title": "Rendered QA turns a strong plan into a shippable deck",
                "role": "Closing",
                "key_message": "Final delivery requires story, visual, and format checks.",
                "evidence": ["references/qa-rubric.md"],
                "visual": "Three-card QA checklist",
                "speaker_note": "Close with the pass/fail signal.",
                "source_refs": ["references/qa-rubric.md"],
                "asset_needs": [],
            },
        ],
    }
    (target / "deck-plan.json").write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")

    print(f"Created Knowledge Cat HTML deck project: {target}")
    print(f"Open: {target / 'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
